[build]
  base = "/"
  publish = "public"
  command = "bundle exec rails assets:precompile && bundle exec rails server -e production"

[context.production]
  command = "bundle exec rails db:migrate"

[context.deploy-preview]
  command = "bundle exec rails db:migrate"

[context.branch-deploy]
  command = "bundle exec rails db:migrate"
