[build]
  base = "/"
  publish = "public"  # This is where your Rails app assets will be compiled and served
  command = "bundle exec rails assets:precompile && bundle exec puma -e production -b 0.0.0.0"

[context.production]
  command = "bundle exec rails db:migrate && bundle exec puma -e production -b 0.0.0.0"
